### ISSUE TITLE
Seminário: Arch Linux

### ISSUE THREAD

**Issue by vinidiasvalerio** [igorsteinmacher/DSL-UTFPR#19]

**Comment by igorsteinmacher** [comment]
Apresentação em 30/08 @vinidiasvalerio @paulobcosta @luisfernandolfc

**Comment by igorsteinmacher** [comment]
Apresentado. Muito bom meninos :+1:

**Comment by igorsteinmacher** [comment]
Apresentado. Muito bom meninos :+1:
